// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSGFl73bAQpNFM1MAOfaxN--7wJsWK5s',
    appId: '1:917260143013:web:b26b0a599fc48b98c8004c',
    messagingSenderId: '917260143013',
    projectId: 'todolist-a9b50',
    authDomain: 'todolist-a9b50.firebaseapp.com',
    storageBucket: 'todolist-a9b50.appspot.com',
    measurementId: 'G-Y7WR4B8HXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQd3lgcDlJBxBP_6DG2y24-3ODK9k6H4',
    appId: '1:917260143013:android:f59ee51a2dbb7d29c8004c',
    messagingSenderId: '917260143013',
    projectId: 'todolist-a9b50',
    storageBucket: 'todolist-a9b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5EG8mvs7BOiiT1JEPsyBnkRmkH3YOpcM',
    appId: '1:917260143013:ios:543ddfc2f7315db7c8004c',
    messagingSenderId: '917260143013',
    projectId: 'todolist-a9b50',
    storageBucket: 'todolist-a9b50.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5EG8mvs7BOiiT1JEPsyBnkRmkH3YOpcM',
    appId: '1:917260143013:ios:1576acae20500ffbc8004c',
    messagingSenderId: '917260143013',
    projectId: 'todolist-a9b50',
    storageBucket: 'todolist-a9b50.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
